+incdir+inc
+incdir+rtl
+incdir+uvm/agent
+incdir+uvm/driver
+incdir+uvm/monitor
+incdir+uvm/scoreboard
+incdir+uvm/sequences
+incdir+uvm/tests
+incdir+uvm/env
+incdir+uvm/tb
rtl/axi_qspi_pkg.sv
rtl/axi_qspi_fifo.sv
rtl/axi_qspi_core.sv
rtl/axi_qspi_axi4_interface.sv
rtl/axi_qspi_mem_interface.sv
rtl/axi_qspi_wrapper.sv
uvm/tb/axi_qspi_axi_if.sv
uvm/tb/axi_qspi_uvm_pkg.sv
uvm/tb/axi_qspi_tb_top.sv
